package com.medsync.entity;

import jakarta.persistence.*;

/**
 * PatientVitals Entity
 *
 * This class represents patient vital signs data.
 * Each object is mapped to a record in the
 * patient_vitals database table.
 *
 * The data is received from IoT devices,
 * simulators, or external healthcare systems.
 */
@Entity
@Table(name = "patient_vitals")
public class PatientVitals {

    /**
     * Primary Key
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique identifier for the patient.
     * Example: P001, P002
     */
    private String patientId;

    /**
     * Patient heart rate in beats per minute (BPM).
     * Normal range: 60 - 100 BPM
     */
    private int heartRate;

    /**
     * Blood oxygen saturation level (SpO2).
     * Normal range: 95% - 100%
     */
    private int spo2;

    /**
     * Body temperature in Celsius.
     * Normal range: 36.5°C - 37.5°C
     */
    private double temperature;

    /**
     * Date and time when the vital data was recorded.
     * Example: 2026-06-19 10:30:00
     */
    private String timestamp;

    /**
     * Patient status based on vital readings.
     * Example:
     * NORMAL
     * WARNING
     * CRITICAL
     */
    private String status;

    /**
     * Default Constructor
     * Required by JPA/Hibernate.
     */
    public PatientVitals() {}

    /**
     * Returns database record ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets database record ID.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns patient ID.
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * Sets patient ID.
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * Returns heart rate.
     */
    public int getHeartRate() {
        return heartRate;
    }

    /**
     * Sets heart rate.
     */
    public void setHeartRate(int heartRate) {
        this.heartRate = heartRate;
    }

    /**
     * Returns SpO2 value.
     */
    public int getSpo2() {
        return spo2;
    }

    /**
     * Sets SpO2 value.
     */
    public void setSpo2(int spo2) {
        this.spo2 = spo2;
    }

    /**
     * Returns body temperature.
     */
    public double getTemperature() {
        return temperature;
    }

    /**
     * Sets body temperature.
     */
    public void setTemperature(double temperature) {
        this.temperature = temperature;
    }

    /**
     * Returns recorded timestamp.
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets recorded timestamp.
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns patient health status.
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets patient health status.
     */
    public void setStatus(String status) {
        this.status = status;
    }
}